version: '3.9'

services:
 mysql:
  image: mysql:latest
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=mypw
  - MYSQL_DATABASE=mysql
  volumes:
  - mysql:/var/lib/mysql
  - mysqlConfig:/etc/mysql

volumes:
  mysql:
  mysqlConfig: